# Generated by Django 5.2.3 on 2025-06-22 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dbp', models.FloatField()),
                ('dap', models.FloatField()),
                ('dn', models.FloatField()),
                ('tmf', models.FloatField()),
                ('tn', models.FloatField()),
                ('wc_total', models.FloatField()),
                ('total_price', models.FloatField()),
            ],
        ),
    ]
