# Generated by Django 5.2.3 on 2025-06-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecalculationlog',
            old_name='tmf',
            new_name='totaldistance',
        ),
        migrations.RemoveField(
            model_name='pricecalculationlog',
            name='dn',
        ),
        migrations.RemoveField(
            model_name='pricecalculationlog',
            name='tn',
        ),
        migrations.AddField(
            model_name='pricecalculationlog',
            name='day',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricecalculationlog',
            name='tend',
            field=models.CharField(default='00:00', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricecalculationlog',
            name='tstart',
            field=models.CharField(default='00:00', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricecalculationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
